### ISSUE TITLE
Build fails with "heap limit allocation failed"

### ISSUE THREAD

**Issue by marc-mueller** [enzonotario/vitepress-openapi#65] opened 2024-10-05 09:58 UTC
### Current behavior

I added two open api specification files to my site configuration. While building the site, it fails with a heap limit allocation failed error as follows:

```
<--- Last few GCs --->

[8528:0000028921749270]    51958 ms: Scavenge 4038.9 (4137.2) -> 4038.5 (4142.0) MB, 5.89 / 0.00 ms  (average mu = 0.723, current mu = 0.560) allocation failure;
[8528:0000028921749270]    53307 ms: Mark-Compact 4042.1 (4142.2) -> 4040.3 (4145.0) MB, 1345.40 / 0.00 ms  (average mu = 0.530, current mu = 0.017) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF7257A39EB node::SetCppgcReference+18459
 2: 00007FF725713238 DSA_meth_get_flags+93160
 3: 00007FF72618C771 v8::Isolate::ReportExternalAllocationLimitReached+65
 4: 00007FF726175EC8 v8::Function::Experimental_IsNopFunction+1336
 5: 00007FF725FD7970 v8::Platform::SystemClockTimeMillis+659328
 6: 00007FF725FD49F8 v8::Platform::SystemClockTimeMillis+647176
 7: 00007FF725FE9D0A v8::Platform::SystemClockTimeMillis+733978
 8: 00007FF725FEA587 v8::Platform::SystemClockTimeMillis+736151
 9: 00007FF725FF8E7F v8::Platform::SystemClockTimeMillis+795791
10: 00007FF725CB9565 v8::CodeEvent::GetFunctionName+116773
11: 00007FF72623E0FE v8::PropertyDescriptor::writable+678094
12: 00007FF6A726D238
```

### Desired behavior

No errors during build

### Steps to reproduce

I added a markdown file like this

```
---
aside: true
outline: [1, 2]
title: <redactedname> API v1
---

<script setup lang="ts">
import { useData } from 'vitepress'
import spec from '../../Services/ServiceClients/swagger/<redactedname>_v1.json'
const { isDark } = useData()
</script>

<OASpec :spec="spec" :hideInfo="true" :hideServers="true" :isDark="isDark" />
```

### Logs and Error Messages

<--- Last few GCs --->

[8528:0000028921749270]    51958 ms: Scavenge 4038.9 (4137.2) -> 4038.5 (4142.0) MB, 5.89 / 0.00 ms  (average mu = 0.723, current mu = 0.560) allocation failure;
[8528:0000028921749270]    53307 ms: Mark-Compact 4042.1 (4142.2) -> 4040.3 (4145.0) MB, 1345.40 / 0.00 ms  (average mu = 0.530, current mu = 0.017) allocation failure; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF7257A39EB node::SetCppgcReference+18459
 2: 00007FF725713238 DSA_meth_get_flags+93160
 3: 00007FF72618C771 v8::Isolate::ReportExternalAllocationLimitReached+65
 4: 00007FF726175EC8 v8::Function::Experimental_IsNopFunction+1336
 5: 00007FF725FD7970 v8::Platform::SystemClockTimeMillis+659328
 6: 00007FF725FD49F8 v8::Platform::SystemClockTimeMillis+647176
 7: 00007FF725FE9D0A v8::Platform::SystemClockTimeMillis+733978
 8: 00007FF725FEA587 v8::Platform::SystemClockTimeMillis+736151
 9: 00007FF725FF8E7F v8::Platform::SystemClockTimeMillis+795791
10: 00007FF725CB9565 v8::CodeEvent::GetFunctionName+116773
11: 00007FF72623E0FE v8::PropertyDescriptor::writable+678094
12: 00007FF6A726D238

### Other Information

During the build, I also get many errors like this:

ReferenceError: localStorage is not defined
    at file:///C:/Repos/Work/<redactedname>/Docs/node_modules/vitepress-theme-openapi/dist/vitepress-theme-openapi.es.js:66959:56
    at Array.map (<anonymous>)
    at setup (file:///C:/Repos/Work/<redactedname>/Docs/node_modules/vitepress-theme-openapi/dist/vitepress-theme-openapi.es.js:66957:43)
    at callWithErrorHandling (C:\Repos\Work\<redactedname>\Docs\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:86:19)
    at setupStatefulComponent (C:\Repos\Work\<redactedname>\Docs\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:6241:25)
    at setupComponent (C:\Repos\Work\<redactedname>\Docs\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:6228:36)
    at renderComponentVNode (C:\Repos\Work\<redactedname>\Docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:376:15)
    at renderVNode (C:\Repos\Work\<redactedname>\Docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:507:14)
    at renderVNodeChildren (C:\Repos\Work\<redactedname>\Docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:523:5)
    at renderElementVNode (C:\Repos\Work\<redactedname>\Docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:567:9)
ReferenceError: localStorage is not defined
    at file:///C:/Repos/Work/<redactedname>/Docs/node_modules/vitepress-theme-openapi/dist/vitepress-theme-openapi.es.js:66959:56
    at Array.map (<anonymous>)
    at setup (file:///C:/Repos/Work/<redactedname>/Docs/node_modules/vitepress-theme-openapi/dist/vitepress-theme-openapi.es.js:66957:43)
    at callWithErrorHandling (C:\Repos\Work\<redactedname>\Docs\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:86:19)
    at setupStatefulComponent (C:\Repos\Work\<redactedname>\Docs\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:6241:25)
    at setupComponent (C:\Repos\Work\<redactedname>\Docs\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:6228:36)
    at renderComponentVNode (C:\Repos\Work\<redactedname>\Docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:376:15)
    at renderVNode (C:\Repos\Work\<redactedname>\Docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:507:14)
    at renderVNodeChildren (C:\Repos\Work\<redactedname>\Docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:523:5)
    at renderElementVNode (C:\Repos\Work\<redactedname>\Docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:567:9)

**Comment by enzonotario** [comment] 2024-10-05 11:18
Can you please share an OpenAPI specificarion that reproduces the error to check this?

**Comment by enzonotario** [comment] 2024-10-05 23:34
@marc-mueller  I was able to reproduce the `localStorage` issue, and it's fixed in [v0.0.3-alpha.34](https://github.com/enzonotario/vitepress-theme-openapi/releases/tag/v0.0.3-alpha.34). Can you please validate the fix?

If the issue persists, please provide a minimal reproduction. I've created a Starter Template for this purpose: https://github.com/enzonotario/vitepress-theme-openapi-starter

Thanks for reporting!

**Comment by marc-mueller** [comment] 2024-10-07 07:41
Thanks for your fast reply and release. I can confirm that the `localStorage` is gone,


However, the heap limit issue is still present:

```
npm run docs:build

> docs:build
> vitepress build


  vitepress v1.3.4

⠦ building client + server bundles...
(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ building client + server bundles...
⠹ rendering pages...
<--- Last few GCs --->

[41248:000001FE568BA660]    51268 ms: Mark-Compact (reduce) 4049.6 (4143.4) -> 4048.2 (4143.7) MB, 2835.31 / 0.00 ms  (average mu = 0.533, current mu = 0.395) allocation failure; scavenge might not succeed
[41248:000001FE568BA660]    53868 ms: Mark-Compact (reduce) 4049.3 (4143.7) -> 4049.0 (4144.4) MB, 2596.25 / 0.00 ms  (average mu = 0.327, current mu = 0.001) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF7257A39EB node::SetCppgcReference+18459
 2: 00007FF725713238 DSA_meth_get_flags+93160
 3: 00007FF72618C771 v8::Isolate::ReportExternalAllocationLimitReached+65
 4: 00007FF726175EC8 v8::Function::Experimental_IsNopFunction+1336
 5: 00007FF725FD7970 v8::Platform::SystemClockTimeMillis+659328
 6: 00007FF725FD49F8 v8::Platform::SystemClockTimeMillis+647176
 7: 00007FF725FE9D0A v8::Platform::SystemClockTimeMillis+733978
 8: 00007FF725FEA587 v8::Platform::SystemClockTimeMillis+736151
 9: 00007FF725FF8E7F v8::Platform::SystemClockTimeMillis+795791
10: 00007FF725CB9565 v8::CodeEvent::GetFunctionName+116773
11: 00007FF72623E0FE v8::PropertyDescriptor::writable+678094
12: 00007FF7262D4661 v8::PropertyDescriptor::writable+1293873
13: 00007FF7262BFCD1 v8::PropertyDescriptor::writable+1209505
14: 00007FF6A72DB4D0
```

My openapi spec is rather big, but still I would consider it a reasonable size for a normal application. If I increase the memory size by using `--max_old_space_size=32768` the build runs for like 15 - 20 minutes and then still fails with a heap size limit error. It looks like it allocates too much memory for larger openapi specifications.

I use the `OASpec` component to render each openapi spec in a page. The markdown page looks like this:

```
---
aside: true
outline: [1, 2]
title: Management API v1
---

<script setup lang="ts">
import { useData } from 'vitepress'
import spec from '../../Services/ServiceClients/swagger/managementserviceclient_v1.json'
const { isDark } = useData()
</script>

<OASpec :spec="spec" :isDark="isDark" />
```

**Comment by enzonotario** [comment] 2024-10-07 16:04
Hi @marc-mueller , I know/suspect we could review all parsing-related code to optimize computation/time, but so far, I just can't reproduce this issue.

1. Can you please share your Big Specification? I tested with [this one](https://github.com/Redocly/redoc/blob/main/demo/big-openapi.json) and it works fine.
2. I suspect it might be related to your PC/OS. So, can you please provide more details about your System? Also, can you try deploying your Docs in Vercel/Netlify/similar? Or, even try it in [StackBlitz](https://stackblitz.com/edit/enzonotario-vitepress-openapi-starter-4jyhpz?file=public%2Fopenapi.json)

**Comment by enzonotario** [comment] 2024-10-13 22:18
Hi @marc-mueller , I've made an optimization when using `OASpec`. It was parsing spec on every Operation. Now it only parses once. Can you please validate it in [v0.0.3-alpha.41](https://github.com/enzonotario/vitepress-openapi/releases/tag/v0.0.3-alpha.41)?

**Comment by marc-mueller** [comment] 2024-10-14 10:33
Thanks for the update! Unfortunately, the large one still fails with a heap limit exception. The smaller one is now building very fast. The large one is about 42k lines of json. I cannot share it publicly, I'll try to build it on other systems as well. Since the build takes so long and results in a heap limit exception, it could also be a recursive reference somewhere which is looping all over. I can also share the swagger definition privately with you if this helps.

**Comment by enzonotario** [comment] 2024-10-14 12:24
Hi @marc-mueller , yes please share the Large Swagger at hi@enzonotario.me , I want to determine whether it's a system issue or something related to code performance

**Comment by JustSamuel** [comment] 2024-10-29 09:33
I also had issues with larger specs, but I just kept upping the `--max_old_space_size` until it worked. However it would result in insanely long build times. But I also read that this could be a `vitepress` issue in general. See the discussion [here](https://github.com/vuejs/vitepress/discussions/1778)

**Comment by enzonotario** [comment] 2024-10-29 16:22
Yes, I also believe that those memory issues are related to VitePress.

However, in this particular case, Marc shared the spec with me, and I discovered a few issues:

- The spec contains circular references, which vitepress-openapi currently struggles to handle gracefully. To address this, I’ve added an option `useTheme({ spec: { avoidCirculars: true } })` to manage these more effectively for now, until we improve the parsing.
- Since the spec is very large, the TryIt and CodeSamples sections become extremely slow when dealing with so many variables. In these cases, it’s better to hide those sections using `useTheme({ operation: { hiddenSlots: ['try-it', 'code-samples'] } })`.
- For very large specs, there’s now an option `useTheme({ spec: { lazyRendering: true } })` to enable lazy rendering. This significantly improves performance, but it makes the app slightly less SEO-friendly.

For now, we need to focus on improving the parsing process and try to reuse already parsed schemas. I’ll close this issue for now, as the memory-related issues related to VitePress. We can concentrate on resolving the parsing-related issues.

Thanks!

**Closed by enzonotario** 2024-10-29 16:22 UTC
Labels: enhancement
